snakes:
    - 99,41
    - 89,53
    - 76,58
    - 66,45
    - 54,31
    - 43,18
    - 40,3
    - 27,5
ladders:
    - 4,25
    - 13,46
    - 33,49
    - 42,63
    - 50,69
    - 62,81
    - 74,92
simulation:
  runs: 2
  players:
    count: 2